[DEFAULT]
DEF_CONF=LINUX
;CREDENTIALS=nicksmart-rb9v-a4e7a5fcc2e1.json
[WINDOWS]
KEY_PATH = murcielago_windows.ppn
MODEL_PATH = porcupine_params_es.pv
[LINUX]
KEY_PATH = Sky-Nick_en_raspberry-pi_v2_1_0.ppn
MODEL_PATH = porcupine_params.pv