# Configuración para ETH
# Convertido de: ParamETH04.py

description: "ETH - Configuraci\xF3n"
name: ETH
parameters:
  MinMaxDistance: 7
  accumulate: 8
  angleDown: 2
  angleUp: 2
  blgDistPercent: 10
  bollinger: 20
  bollingerClose: 15
  bollingerDst: 10
  closeAcumvalue: 0
  closeAngleDiff: 2
  closeProfit: 10
  controlWin: true
  difference: 5
  draw: false
  emaMinDst: 10
  enableBollingerClose: true
  flowDiffInterval: 10
  hourOffset: -4
  ignoreProb: false
  ima1: 3
  ima1maxDistance: 0
  ima1minDistance: 0
  ima2: 10
  ima3: 13
  ima3minDistance: 0
  ima4: 2
  maxAngleDown: 88
  maxAngleUp: 88
  maxMEDNormal: 0
  maxOpenCount: 7
  maxSTDNormal: 0
  maxWeekBootDist: 70
  medstdmaxDiff: 20
  medstdminDiff: 0
  minAngleFlow: 5
  minAngleFlowCounter: 3
  minAngleIma1: 10
  minMEDNormal: 0
  minSTDNormal: 0
  minflowDiff: 5
  minimunCloseAmount: 5
  operate: true
  percent_distance: 6
  percent_min_distance: 1
  rangehours:
  - 16
  - 9
  reevaluateAction: false
  relativeDistance: 2
  relativeDistanceMultiplicator: 0
  round: 5
  tendence_distance: 4
  tendence_distance_moment: 6
  tendence_measure: 0
  unit: 0
  valueIndDIST: 1
  verifyMarketOpen: false
  weekDistanceMedDistance: 1
  weekDistanceSTDDistance: 0
  weekInterval: 10
  weekMEDMinLevel: 10
  weekMindiff: 10
  weekend: true
