class Constants:

    VALUE = 'VALUE'
    NAME = 'NAME'
    ANALISIS_NAME = 'ANALISIS_NAME'
    FLUJO = 'FLUJO'
    FLUJO_COUNT = 'FLUJOCOUNT'
    ACUMULADO = 'ACUMULADO'
    ACUMULADO_ABS = 'ACUMULADO_ABS'
    FLUJO_SUBE = "SUBE"
    FLUJO_BAJA = "BAJA"
    FLUJO_MANTIENE = "MANTIENE"
    RELATIVE_MIN = "RELATIVE_MIN"
    RELATIVE_PREV_MIN = "RELATIVE_PREV_MIN"
    RELATIVE_PREV_MIN_DIST = "RELATIVE_PREV_MIN_DIST"
    RELATIVE_MIN_DIST = "RELATIVE_MIN_DIST"
    RELATIVE_MAX = "RELATIVE_MAX"
    RELATIVE_PREV_MAX = "RELATIVE_PREV_MAX"
    RELATIVE_PREV_MAX_DIST = "RELATIVE_PREV_MAX_DIST"
    RELATIVE_MAX_DIST = "RELATIVE_MAX_DIST"
    RELATIVE = "RELATIVE"
    IND_REL_FCST = "IND_REL_FCST"
    PREVIOUS_DIST = "PREVIOUS_DIST"
    EVAl_NAME = "EVAL_NAME"
    EVAl_CLOSE_ACUM = "EVAl_CLOSE_ACUM"
    EVAl_CLOSE_DIFF = "EVAl_CLOSE_DIFF"
    EVAl_ACUM = "EVAl_ACUM"
    FLOW_DIFF = "FLOW_DIFF"

    DATE = 'DATE'

    IMA5MA20 = 'IMA5MA20'
    IMA5MA20_DST = 'IMA5MA20_DST'
    IMA_NEW = 'IMA_NEW'
    IMA1 = 'IMA1'
    IMA_NEW_POINT = 'IMA_NEW_POINT'
    IMA_NEW_BUY = 'IMA_NEW_BUY'
    IMA_NEW_SELL = 'IMA_NEW_SELL'
    IMA_NEW_WAIT = 'IMA_NEW_WAIT'

    IMA1_BUY = 'IMA1_BUY'
    IMA1_SELL = 'IMA1_SELL'
    IMA1_WAIT = 'IMA1_WAIT'
    IMA1_DISTANCE ='IMA1_DISTANCE'
    # INDICADOR DE MERCADO PARA SABER SI CRUZO LA MEDIA 5 SOBRE LA MEDIA 20 EN UN DETERMINADO MOMENTO
    MARKET_TENDENCE = 'MARKET_TENDENCE'
    MARKET_TENDENCE_UP = 'MARKET_TENDENCE_UP'
    MARKET_TENDENCE_DOWN = 'MARKET_TENDENCE_DOWN'
    MARKET_TENDENCE_UNDEF = 'MARKET_TENDENCE_UNDEF'
    INDICATOR = 'INDICATOR'
    INDICATOR_TENDENCE = 'INDICATOR_TENDENCE'
    INDICATOR_DISTANCE = 'INDICATOR_DISTANCE'
    INDICATOR_MED = 'INDICATOR_MED'
    INDICATOR_MED_DAY = 'INDICATOR_MED_DAY'
    INDICATOR_MED_DAYS = 'INDICATOR_MED_DAYS'
    INDICATOR_MED_MOMENT = 'INDICATOR_MED_MOMENT'
    INDICATOR_MED_MOMENT_VALUE = 'INDICATOR_MED_MOMENT_VALUE'
    INDICATOR_STD = 'INDICATOR_STD'
    INDICATOR_STD_DAY = 'INDICATOR_STD_DAY'
    INDICATOR_STD_DAYS = 'INDICATOR_STD_DAYS'
    INDICATOR_MED_STD = 'INDICATOR_MED_STD'

    VALUE_DIFFMED = 'VALUE_DIFFMED'
    IND_MED_DAY = 'IND_MED_DAY'
    IND_SUM_UP = 'IND_SUM_UP'
    IND_NUM_UP = 'IND_NUM_UP'
    IND_SUM_DOWN = 'IND_SUM_DOWN'
    IND_NUM_DOWN = 'IND_NUM_DOWN'

    IND_SUM_UP_DAYS = 'IND_SUM_UP_DAYS'
    IND_NUM_UP_DAYS = 'IND_NUM_UP_DAYS'
    IND_SUM_DOWN_DAYS = 'IND_SUM_DOWN_DAYS'
    IND_NUM_DOWN_DAYS = 'IND_NUM_DOWN_DAYS'

    SIMULATION = 'SIMULATION'
    ISDBDATA = 'ISDBDATA'
    ONLY_START_END = 'ONLY_START_END'
    RSI = 'RSI'
    RSI_PREV5 = 'RSI_PREV5'
    RSI_DIFF = 'RSI_DIFF'
    RSI_SLOPE = 'RSI_SLOPE'
    RSI_ACCEL = 'RSI_ACCEL'
    RSI_SCORE = 'RSI_SCORE'
    RSI_SIGNAL = 'RSI_SIGNAL'
    SMA_FAST = 'SMA_FAST'
    SMA_SLOW = 'SMA_SLOW'
    MACD = 'MACD'
    MACD_SIGNAL = 'MACD_SIGNAL'
    MACD_SIGNAL_OK = 'MACD_SIGNAL_OK'
    SMA_SIGNAL = 'SMA_SIGNAL'
    ACTION_TEST = 'ACTION_TEST'
    MEDIA = 'MEDIA'
    MEDIA_MOMENT = 'MEDIA_MOMENT'
    STD_MOMENT = 'STD_MOMENT'
    STDDESV = 'STDDESV'
    MEDSTDDIFF = 'MEDSTDDIFF'
    ANGLE = 'ANGLE'
    HOURLY_ANGLE = 'HOURLY_ANGLE'
    HOURLY_ANGLE_MED = 'HOURLY_ANGLE_MED'
    HOURLY_ANGLE_MED_PREV = 'HOURLY_ANGLE_MED_PREV'
    ANGLE_PREV = 'ANGLE_PREV'
    ANGLE_COUNTER = 'ANGLE_COUNTER'
    ANGLEm1 = 'ANGLEm1'
    ANGLEm21 = 'ANGLEm21'
    IMA1EMADIFF = 'IMA1EMADIFF'


    INDICATOR_RELATIVE_UP = 'INDICATOR_RELATIVE_UP'
    INDICATOR_RELATIVE_DOWN = 'INDICATOR_RELATIVE_DOWN'
    INDICATOR_RELATIVE_DOWN_CHANGE = 'INDICATOR_RELATIVE_DOWN_CHANGE'
    INDICATOR_RELATIVE_UP_CHANGE = 'INDICATOR_RELATIVE_UP_CHANGE'
    INDICATOR_RELATIVE_WAIT = 'INDICATOR_RELATIVE_WAIT'

    IND_REL_FCST_UP ="IND_REL_FCST_UP"
    IND_REL_FCST_UP_INV_REL ="IND_REL_FCST_UP_INV_REL"
    IND_REL_FCST_DOWN_INV_REL ="IND_REL_FCST_DOWN_INV_REL"
    IND_REL_FCST_PRE_UP ="IND_REL_FCST_PRE_UP"
    IND_REL_FCST_PRE_DOWN ="IND_REL_FCST_PRE_DOWN"
    IND_REL_FCST_DOWN ="IND_REL_FCST_DOWN"
    IND_REL_FCST_WAIT ="IND_REL_FCST_WAIT"
    IND_REL_FCST_NOTINIT ="IND_REL_FCST_NOTINIT"
    IND_REL_FCST_STD ="IND_REL_FCST_STD"
    IND_REL_FCST_MED ="IND_REL_FCST_MED"
    IND_REL_FCST_MIN ="IND_REL_FCST_MIN"
    IND_REL_FCST_MAX ="IND_REL_FCST_MAX"
    IND_REL_FCST_PERCENT ="IND_REL_FCST_PERCENT"
    IND_REL_FCST_PREV_PERCENT ="IND_REL_FCST_PREV_PERCENT"
    IND_REL_FCST_PRE_MED ="IND_REL_FCST_PRE_MED"
    IND_REL_FCST_PRE_STD ="IND_REL_FCST_PRE_STD"
    IND_REL_FCST_DISTANCE ="IND_REL_FCST_DISTANCE"

    IND_REL_PERCENT_MED = "IND_REL_PERCENT_MED"
    IND_REL_PERCENT_STD = "IND_REL_PERCENT_STD"

    IND_PROB_FLOW = "IND_PROB_FLOW"

    #CLOSE NXT
    CLOSE_NXT_UP = "CLOSE_NXT_UP"
    CLOSE_NXT_DOWN = "CLOSE_NXT_DOWN"
    CLOSE_NXT_MIDDLE = "CLOSE_NXT_MIDDLE"



    # ACTIONS
    ACTION_BUY = 'BUY'
    ACTION_SELL = 'SELL'
    ACTION_WAIT = 'WAIT'
    ACTION_CLOSE = 'CLOSE'

    INDICATOR_EMA = 'INDICATOR_EMA'
    INDICATOR_EMA50 = 'INDICATOR_EMA50'
    INDICATOR_EMA50_DST = 'INDICATOR_EMA50_DST'
    EMA_DST = 'EMA_DST'
    EMA10_ANGLE = 'EMA10_ANGLE'
    EMA10_SLOPE = 'EMA10_SLOPE'
    EMA20_SLOPE = 'EMA20_SLOPE'
    EMA_SPREAD = 'EMA_SPREAD'
    EMA_CROSS_COUNT = 'EMA_CROSS_COUNT'
    PRICE_RANGE_PERCENT = 'PRICE_RANGE_PERCENT'
    CURRVAL_EMA_DST = 'CURRVAL_EMA_DST'
    INDICATOR_EMA_CHECK = 'INDICATOR_EMA_CHECK'
    INDICATOR_EMA_BUY = 'INDICATOR_EMA_BUY'
    INDICATOR_EMA_SELL = 'INDICATOR_EMA_SELL'
    INDICATOR_EMA_WAIT = 'INDICATOR_EMA_WAIT'

    IND_BLG = 'IND_BLG'
    IND_BLG_MED_BUY = 'IND_BLG_MED_BUY'
    IND_BLG_MED_SELL = 'IND_BLG_MED_SELL'
    IND_BLG_MED_WAIT = 'IND_BLG_MED_WAIT'
    IND_BLG_MED_DST = 'IND_BLG_MED_DST'
    IND_BLG_UPPER_DST = 'IND_BLG_TOP_DST'
    IND_BLG_UPPER_DST_PERCENT = 'IND_BLG_UPPER_DST_PERCENT'
    IND_BLG_LOWER_DST = 'IND_BLG_LOWER_DST'
    IND_BLG_LOWER_DST_PERCENT = 'IND_BLG_LOWER_DST_PERCENT'
    IND_BLG_MIDDLE_DST_PERCENT = 'IND_BLG_MIDDLE_DST_PERCENT'
    BLG_BANDWIDTH = 'BLG_BANDWIDTH'



    # INDICADORES
    INDICATOR_EMPTY = 'EMPTY'
    INDICATOR_BUY = 'I_BUY'
    INDICATOR_WAIT = 'WAIT'
    INDICATOR_BUYX = 'I_BUYX'
    INDICATOR_SELL = 'I_SELL'
    INDICATOR_SELLX = 'I_SELLX'

    # INDICADOR DE TENDENCIA EN BASE A LA MEDIA Y DETERMINA EL ANGULO DE TIEMPO
    INDICATOR_T_UP = 'INDICATOR_T_UP'
    INDICATOR_T_DOWN = 'INDICATOR_T_DOWN'
    INDICATOR_T_WAIT = 'INDICATOR_T_WAIT'

    INDICATOR_TM_UP = 'INDICATOR_TM_UP'
    INDICATOR_TM_DOWN = 'INDICATOR_TM_DOWN'
    INDICATOR_TM_WAIT = 'INDICATOR_TM_WAIT'
    INDICATOR_TM_UNDEF = 'INDICATOR_TM_UNDEF'

    INDICATOR_TSTD_HIGH = 'INDICATOR_TSTD_HIGH'
    INDICATOR_TSTD_LOW = 'INDICATOR_TSTD_LOW'
    INDICATOR_TSTD_MID = 'INDICATOR_TSTD_WAIT'
    INDICATOR_TSTD_UNDEF = 'INDICATOR_TSTD_UNDEF'

    INDICATOR_M_STD_UP = 'INDICATOR_M_STD_UP'
    INDICATOR_M_STD_DOWN = 'INDICATOR_M_STD_DOWN'
    INDICATOR_M_STD_WAIT = 'INDICATOR_M_STD_WAIT'

    WEEK_FLOW_MED_LEVEL_LOW = 'WEEK_FLOW_MED_LEVEL_LOW'
    WEEK_FLOW_MED_LEVEL_HIGH = 'WEEK_FLOW_MED_LEVEL_HIGH'
    WEEK_FLOW_MED_LEVEL_MID = 'WEEK_FLOW_MED_LEVEL_MID'
    WEEK_FLOW_MED_LEVEL_UNDEF = 'WEEK_FLOW_MED_LEVEL_UNDEF'


    ALTA = 'ALTA'
    BAJA = 'BAJA'
    NORMAL = 'NORMAL'

    WEEK_FLOW = 'WEEK_FLOW'
    WEEK_DIR = 'WEEK_DIR'
    WEEK_DIR_FLOW_PREV = 'WEEK_DIR_FLOW_PREV'
    WEEK_MIN_DIR = 'WEEK_MIN_DIR'
    WEEK_MAX_DIR = 'WEEK_MAX_DIR'
    WEEK_DIR_TOP_DST = 'WEEK_DIR_TOP_DST'
    MONTH_DIR_TOP_DST = 'MONTH_DIR_TOP_DST'
    WEEK_DIR_BOT_DST = 'WEEK_DIR_BOT_DST'
    WEEK_DIR_BOT_DST_NEW = 'WEEK_DIR_BOT_DST_NEW'
    MONTH_DIR_BOT_DST = 'MONTH_DIR_BOT_DST'
    BOT_DST_BLG = 'BOT_DST_BLG'
    WEEK_DIR_BOT_DST_PREV = 'WEEK_DIR_BOT_DST_PREV'
    WEEK_DIR_FLOW_DIFF = 'WEEK_DIR_FLOW_DIFF'
    WEEK_DIR_FLOW = 'WEEK_DIR_FLOW'
    WEEK_FLOW_PREV = 'WEEK_FLOW_PREV'
    WEEK_FLOW_PREV_MED = 'WEEK_FLOW_PREV_MED'
    WEEK_FLOW_DIFF = 'WEEK_FLOW_DIFF'
    WEEK_FLOW_ABSVAL = 'WEEK_FLOW_ABSVAL'
    WEEK_FLOW_MED = 'WEEK_FLOW_MED'
    WEEK_FLOW_STD = 'WEEK_FLOW_STD'
    WEEK_FLOW_MED_LEVEL = 'WEEK_FLOW_MED_LEVEL'
    WEEK_FLOW_UP = 'WEEK_FLOW_UP'
    WEEK_FLOW_UP_LOW = 'WEEK_FLOW_UP_LOW'
    WEEK_FLOW_DOWN = 'WEEK_FLOW_DOWN'
    WEEK_FLOW_DOWN_LOW = 'WEEK_FLOW_DOWN_LOW'
    WEEK_FLOW_UNDEF = 'WEEK_FLOW_UNDEF'
    WEEK_FLOW_NOTINIT = 'WEEK_FLOW_NOTINIT'
    WEEK_DIR_BOT_DST_MED = 'WEEK_DIR_BOT_DST_MED'
    MONTH_DIR_BOT_DST_MED = 'MONTH_DIR_BOT_DST_MED'
    WEEK_DIR_BOT_DST_MED_NEW = 'WEEK_DIR_BOT_DST_MED_NEW'
    WEEK_DIR_BOT_DST_MED_NEW_FLOW = 'WEEK_DIR_BOT_DST_MED_NEW_FLOW'


    CURRENT_ACTION = 'CURRENT_ACTION'
    CHANGE_ACTION = 'CHANGE_ACTION'
    NEW_ACTION = 'NEW_ACTION'
    ACTION_MIN = 'ACTION_MIN'
    ACTION_COUNT = 'ACTION_COUNT'
    ACTION_ACUM= 'ACTION_ACUM'
    ACTION_ACUM_END= 'ACTION_ACUM_END'
    ACTION_MIN_DIST = 'ACTION_MIN_DIST'
    ACTION_MAX = 'ACTION_MAX'
    ACTION_MAX_DIST = 'ACTION_MAX_DIST'
    START_ACTION_VAL = 'START_ACTION_VAL'
    ACTION_DISTANCE = 'ACTION_DISTANCE'
    DBID = 'DBID'
    REVENUE = 'REVENUE'
    PROFIT = 'PROFIT'
    PROTECT = 'PROTECT'
    MESSAGES = 'MESSAGES'
    INICIO_NAME = 'INICIO_NAME'
    BLG_MA_MEAN = 'BLG_MA_MEAN'

    #direction
    SIMULATION = 'SIMULATION'
    DIRECTION = 'DIRECTION'
    MIN_DIR = 'MIN_DIR'
    MAX_DIR = 'MAX_DIR'
    INDI_DIR = 'INDI_DIR'

    DIR_UP = 'DIR_UP'
    DIR_PRE_UP = 'DIR_PRE_UP'
    DIR_DOWN = 'DIR_DOWN'
    DIR_PRE_DOWN = 'DIR_PRE_DOWN'
    DIR_CHANGE = 'DIR_CHANGE'
    DIR_CHANGE_UP = 'DIR_CHANGE_UP'
    DIR_CHANGE_DOWN = 'DIR_CHANGE_DOWN'
    DIR_WAIT = 'DIR_WAIT'
    INTERVAL = 'INTERVAL'


    DOWN_LOW = "DOWN_LOW"
    DOWN_HIGH = "DOWN_HIGH"
    UP_HIGH = "UP_HIGH"
    UP_LOW = "UP_LOW"

    MARKET_ANGLE = "MARKET_ANGLE"
    ANGLE_EMA = "ANGLE_EMA"
    ANGLE_IMA1 = "ANGLE_IMA1"
    ANGLE_IMA1_PREV = "ANGLE_IMA1_PREV"
    ANGLE_IMA1_COUNTER = "ANGLE_IMA1_COUNTER"
    ANGLE_EMA20 = "ANGLE_EMA20"
    ANGLE_EMAm1 = "ANGLE_EMAm1"
    ANGLE_EMA_FLOW = "ANGLE_EMA_FLOW"
    ANGLE_FLOW = "ANGLE_FLOW"
    MARKET_ANGLE_TANG = "MARKET_ANGLE_TANG"

    BLG_MA_X= "BLG_MA_X"
    BLG_MA_VAL= "BLG_MA_VAL"
    EMA10_BLG_DST = 'EMA10_BLG_DST'
    EMA20_BLG_DST = 'EMA20_BLG_DST'

    MIN_WEEK = 'MIN_WEEK'
    MAX_WEEK = 'MAX_WEEK'
    MIN_MONTH = 'MIN_MONTH'
    MAX_MONTH = 'MAX_MONTH'
    TIME_FROM_OPEN = 'TIME_FROM_OPEN'

    # Order Flow / Footprint
    ORDER_FLOW_DELTA = 'ORDER_FLOW_DELTA'
    ORDER_FLOW_CUM_DELTA = 'ORDER_FLOW_CUM_DELTA'
    ORDER_FLOW_RATIO = 'ORDER_FLOW_RATIO'
    ORDER_FLOW_SCORE = 'ORDER_FLOW_SCORE'
    ORDER_FLOW_SIGNAL = 'ORDER_FLOW_SIGNAL'
    ORDER_FLOW_IMBALANCE = 'ORDER_FLOW_IMBALANCE'

    # Market Trend (Tendencia de mercado)
    MARKET_TREND_DIRECTION = 'MARKET_TREND_DIRECTION'
    MARKET_TREND_INTENSITY = 'MARKET_TREND_INTENSITY'
    MARKET_TREND_SCORE = 'MARKET_TREND_SCORE'
    MARKET_TREND_SLOPE_3D = 'MARKET_TREND_SLOPE_3D'
    MARKET_TREND_SLOPE_7D = 'MARKET_TREND_SLOPE_7D'
    MARKET_TREND_PCT_CHANGE_3D = 'MARKET_TREND_PCT_CHANGE_3D'
    MARKET_TREND_PCT_CHANGE_7D = 'MARKET_TREND_PCT_CHANGE_7D'
    MARKET_TREND_CONSISTENCY = 'MARKET_TREND_CONSISTENCY'

    TREND_UP = 'TREND_UP'
    TREND_DOWN = 'TREND_DOWN'
    TREND_NEUTRAL = 'TREND_NEUTRAL'

    TREND_INTENSITY_HIGH = 'ALTA'
    TREND_INTENSITY_MED = 'MEDIA'
    TREND_INTENSITY_LOW = 'BAJA'
